### PR TITLE
A series of small changes

### PR DESCRIPTION
**Pull request by michaelenger**
These are some changes that have been bothering me lately:

* Changing how the list of videos is shown (list/grid) is now persisted in local storage
* The "randomize" button reloads the page - randomizing the current video as well as scrolling to the top
* Fix an issue where clicking on a video in a show page will forget what page you were on
* Have a placeholder image when thumbnails are loading so content doesn't get pushed around
* Fix pagination buttons not behaving properly after the move to Svelte 5
* Change the amount of videos shown per page under a show to be divisible by four so that it doesn't leave a video dangling on large screens

Finally I changed the default video source to be YouTube since the video embed from Internet Archive is still down :(

### CODE REVIEW

**Review by vegeta897 — CHANGES_REQUESTED** [review]
Nice work!

Possible issue: clicking the random button does update the URL and change the video, but it does not generate a new list of random videos. Refreshing the page manually does this, so I feel the button should do it too.

**Comment by michaelenger** [comment]
@vegeta897 OMG, thank you for noticing! It should be fixed now.

**Comment by vegeta897** [comment]
Sorry, I only just noticed the "Randomize" button at the bottom of the page. I was talking about the "Random" tab in the nav header. SvelteKit skips the page component initialization when not doing a full refresh so the video list stays the same when you click this link while already on a random video.

Maybe that's intended, but the behavior differing from hitting F5 bugs me.

This can be fixed by adding this to `src/routes/random/[video]/+page.svelte`:
```ts
onNavigate(()=> {
    videos = dataStore.getRandomVideos(12)
})
```

But I wish there was a more elegant way. Adding `data-sveltekit-reload` to the nav link would also do the trick, but then it would make the whole app reload which is overkill. I'll leave it up to you.

**Comment by michaelenger** [comment]
@vegeta897 Thank you for catching that and figuring out the solution! I've implemented it and it seems to work correctly now (with the random link and the randomize button). Things being so tricky is due to my insistence that we redirect to a URL that contains the video ID, my reasoning being that you can then share the video with someone if you want :P

**Review by vegeta897 — APPROVED** [review]

**Comment by vegeta897** [comment]
> Things being so tricky is due to my insistence that we redirect to a URL that contains the video ID, my reasoning being that you can then share the video with someone if you want :P

The way the URL works here is great, I'm glad you made it this way.

**Pull request merged**
